#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'session'
    style = 'plain'
    template = ' {{ if .SSHSession }} {{ end }} '
    foreground = 'p:grey'

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    template = '{{ if .Env.TMUX }}tmux{{ end }}'
    foreground = 'p:grey'

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    template = '{{ path .Path .Location }}'
    background = ''
    foreground = 'p:green'

    [blocks.segments.properties]
      style = 'full'

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    type = 'git'
    style = 'powerline'
    powerline_symbol = ''
    foreground_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}p:black{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:white{{ end }}', '{{ if gt .Ahead 0 }}p:white{{ end }}']
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}p:nyanza{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:red{{ end }}', '{{ if gt .Ahead 0 }}p:red{{ end }}', '{{ if gt .Behind 0 }}p:nyanza{{ end }}']
    template = ' {{ if .UpstreamURL }}{{ url .UpstreamIcon .UpstreamURL }} {{ end }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} '
    background = 'p:green'
    foreground = 'p:black'

    [blocks.segments.properties]
      branch_max_length = 25
      fetch_status = true
      fetch_upstream_icon = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}red{{end}}",
      "{{if eq .Code 0}}p:white{{end}}"
    ]
    template = '❯'

# [[blocks]]
#   type = 'prompt'
#   alignment = 'right'
#   overflow = 'hidden'
#
#   [[blocks.segments]]
#     type = 'executiontime'
#     style = 'plain'
#     foreground = 'p:cyan'
#     template = '{{ .FormattedMs }}'
#     
#     [[blocks.segments.properties]]
#       threshold = 500
#       style = 'austin'

#   [[blocks.segments]]
#     type = 'root'
#     style = 'powerline'
#     powerline_symbol = ''
#     template = '  '
#     background = 'p:nyanza'
#     foreground = 'p:white'
#     Text = ''
#     Duration = 0
#     NameLength = 0
#
[secondary_prompt]
  template = '<p:nyanza,transparent>...</> '
  background = 'transparent'
  foreground = 'p:black'

[transient_prompt]
foreground = 'p:grey'
template = '~ '

[palette]
  black = '#000000'
  cyan = '#4EFFEF'
  green = '#A7C4A0'
  grey = '#2C3539'
  nyanza = '#DAF7DC'
  red = '#BE2562'
  white = '#E0DEF4'
